# Escuela Politécnica Nacional
### Proyecto N° 1
### Integrantes
#### Carlos Vasquez 
#### Gustavo Aconda

In [1]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv("Datasetproyecto.csv")

In [9]:
df.head()

,Puesto Institucional,Grado jerárquico \no escala al que pertenece el puesto,Remuneración \nmensual unificada,Remuneración \nunificada (anual),Décimo \nTercera Remuneración,Décima \nCuarta Remuneración,Horas \nsuplementarias y extraordinarias,Encargos y \nsubrogaciones,Total \ningresos adicionales
0,ANALISTA DE GESTION DE ABASTECIMIENTO,3,"1,755.00","21,060.00",146.25,31.25,0.00,0.00,177.50
1,SUPERINTENDENTE DE MANTENIMIENTO,6,"5,250.00","63,000.00",437.50,31.25,0.00,0.00,468.75
2,SUPERVISOR RCRS,5,"3,300.00","39,600.00",275.00,31.25,0.00,0.00,306.25
3,MENSAJERO,1,962.00,"11,544.00",80.17,31.25,0.00,0.00,111.42
4,AUXILIAR DE CAFETERIA,1,779.00,"9,348.00",64.92,31.25,0.00,0.00,96.17
5,AUXILIAR DE CAFETERIA,1,784.00,"9,408.00",65.33,31.25,0.00,0.00,96.58
6,MENSAJERO,1,784.00,"9,408.00",65.33,31.25,0.00,0.00,96.58
7,JEFE DE CONTROL DE QUIMICOS,6,"6,146.00","73,752.00",512.17,31.25,0.00,0.00,543.42
8,ASISTENTE ADMINISTRATIVA,2,"1,100.00","13,200.00",91.67,31.25,0.00,0.00,122.92
9,ASISTENTE DE ARCHIVO,2,"1,131.00","13,572.00",94.25,31.25,0.00,0.00,125.50
10,ASISTENTE DE ARCHIVO,2,"1,284.00","15,408.00",107.00,31.25,0.00,0.00,138.25
11,JEFE DE CAMPO,7,"6,100.00","73,200.00",508.33,31.25,0.00,0.00,539.58
12,RESERVORISTA,5,"4,213.65","50,563.80",351.14,31.25,0.00,0.00,382.39
13,TÉCNICO ELÉCTRICO (PLANTA DE GENERACIÓN),3,"2,257.00","27,084.00",188.08,31.25,0.00,0.00,219.33
14,INGENIERO DE CORROSIÓN Y QUÍMICOS,5,"3,217.00","38,604.00",268.08,31.25,0.00,0.00,299.33
15,SUPERVISOR DE INSTRUMENTACIÓN,5,"4,097.00","49,164.00",357.78,31.25,196.31,0.00,585.34
16,SUPERINTENDENTE DE RCRS ( E ),6,"3,849.00","46,188.00",320.75,31.25,0.00,512.00,864.00
17,BODEGUERO,2,"1,418.00","17,016.00",124.08,31.25,70.90,0.00,226.23
18,SUPERINTENDENTE DE OPERACIONES ( S ),6,"3,360.00","40,320.00",280.00,31.25,0.00,"1,607.00","1,918.25"
19,SUPERINTENDENTE DE SEGURIDAD,5,"4,361.00","52,332.00",363.42,31.25,0.00,0.00,394.67